In [3]:
import mysql.connector
from pathlib import Path
import pandas as pd

In [5]:
files = Path("data/spcsv").glob("*.csv")

In [ ]:
for f in files:
    df = pd.read_csv(f)

In [19]:
df = pd.read_csv(next(files))
#df["MENU_HINT"]
#day = df[['MENU_HINT'], ['EVENT_DT']]
df

,EVENT_ID,MENU_HINT,EVENT_NAME,EVENT_DT,SELECTION_ID,SELECTION_NAME,WIN_LOSE,BSP,PPWAP,MORNINGWAP,PPMAX,PPMIN,IPMAX,IPMIN,MORNINGTRADEDVOL,PPTRADEDVOL,IPTRADEDVOL
0,126573637,GB / Hayd 3rd Sep,5f Hcap,03-09-2016 16:00,6318060,Englishman,0,10.748123,10.479351,13.762907,16.01,8.40,1000.0,11.00,3880.02,59477.48,1778.66
1,126573637,GB / Hayd 3rd Sep,5f Hcap,03-09-2016 16:00,6593388,Robot Boy,0,7.400000,7.535535,8.840896,9.34,6.60,1000.0,4.00,1588.00,98554.88,9492.06
2,126573644,GB / Hayd 3rd Sep,6f Grp1,03-09-2016 16:30,8787985,Mehronissa,0,29.094224,28.166307,55.429394,83.17,25.00,1000.0,3.20,1792.68,36243.24,4396.60
3,126573651,GB / Hayd 3rd Sep,1m6f Hcap,03-09-2016 17:05,10354079,Spinners Ball,0,8.870416,10.734499,10.009873,13.50,9.60,1000.0,8.00,357.14,34393.70,7575.84
4,126573609,GB / Hayd 3rd Sep,1m2f Hcap,03-09-2016 13:50,9659880,Motdaw,1,13.699476,15.150991,16.948815,60.00,13.50,14.0,1.01,1830.08,21537.02,58433.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,126612185,GB / Thirsk 3rd Sep,1m4f Hcap,03-09-2016 17:00,7269235,Tamayuz Magic,1,7.400000,7.493973,8.460143,10.08,7.00,32.0,1.01,246.62,54721.62,119011.02
395,126612190,GB / Thirsk 3rd Sep,1m Mdn Stks,03-09-2016 17:35,5005939,Organza,0,3.614995,3.799100,4.274368,4.70,3.65,990.0,1.68,473.04,141512.08,22961.94
396,126612195,GB / Thirsk 3rd Sep,6f Hcap,03-09-2016 18:05,8992504,Inexes,0,6.888875,6.281005,4.981073,7.60,4.43,1000.0,4.40,2335.12,88056.48,4280.76
397,126613085,GB / Strat 3rd Sep,2m2f Hcap Hrd,03-09-2016 13:55,6498868,Seeyouallincoppers,0,5.700000,4.968192,3.613109,5.60,3.35,1000.0,4.00,2189.88,49885.92,18382.68
398,126613090,GB / Strat 3rd Sep,2m3f Nov Chs,03-09-2016 14:30,4110179,Finch Flyer,0,124.921099,133.669802,172.055060,300.00,55.00,1000.0,60.00,312.52,8908.26,2649.50

In [28]:
event = df[["EVENT_DT", "MENU_HINT"]]
event["event_date"] = pd.to_datetime(event["EVENT_DT"]).dt.date
event["location"] = event["MENU_HINT"].map(lambda s: s.split(" ")[2])
event = event[["event_date", "location"]].drop_duplicates()
event

    event_date location
0   2016-03-09     Hayd
9   2016-03-09    Ascot
17  2016-03-09     Kemp
25  2016-03-09     Wolv
36  2016-03-09   Thirsk
44  2016-03-09    Strat

In [34]:
race = df[["EVENT_ID", "EVENT_NAME", "EVENT_DT"]]
race["race_id"] = race["EVENT_ID"]
race["race_time"] = pd.to_datetime(race["EVENT_DT"])
race["length_furlongs"] = race["event_name"].map(lambda s: s.split(" ")[0].split(
race["race_type"] = race["EVENT_NAME"].map(lambda s: s.split(" ", 1)[1])
race

,EVENT_ID,EVENT_NAME,EVENT_DT,race_id,race_time,race_type
0,126573637,5f Hcap,03-09-2016 16:00,126573637,2016-03-09 16:00:00,Hcap
1,126573637,5f Hcap,03-09-2016 16:00,126573637,2016-03-09 16:00:00,Hcap
2,126573644,6f Grp1,03-09-2016 16:30,126573644,2016-03-09 16:30:00,Grp1
3,126573651,1m6f Hcap,03-09-2016 17:05,126573651,2016-03-09 17:05:00,Hcap
4,126573609,1m2f Hcap,03-09-2016 13:50,126573609,2016-03-09 13:50:00,Hcap
...,...,...,...,...,...,...
394,126612185,1m4f Hcap,03-09-2016 17:00,126612185,2016-03-09 17:00:00,Hcap
395,126612190,1m Mdn Stks,03-09-2016 17:35,126612190,2016-03-09 17:35:00,Mdn Stks
396,126612195,6f Hcap,03-09-2016 18:05,126612195,2016-03-09 18:05:00,Hcap
397,126613085,2m2f Hcap Hrd,03-09-2016 13:55,126613085,2016-03-09 13:55:00,Hcap Hrd
398,126613090,2m3f Nov Chs,03-09-2016 14:30,126613090,2016-03-09 14:30:00,Nov Chs

In [4]:
cnx = mysql.connector.connect(user="root", password="", host="127.0.0.1", database="BetfairSP")
cursor = cnx.cursor()

ProgrammingError: 1049 (42000): Unknown database 'BetfairSP'